
#define ID_RESOURCES       100
#define IDM_ACTIONS        110
#define IDM_EXPORTTEXT     120
#define IDM_CHANGEFONT     130

#define ID_MLE             300

#define IDM_EXIT           400
#define IDM_SEARCH         500

#define IDDLG_GETSRCHSTRING   600
#define IDD_TEXT_TITLE        610
#define IDD_DETAILS_BOX       620
#define IDD_TEXT_SEARCHSTRING 630
#define IDD_SEARCHSTRING      640
#define IDD_BTN_OK            650
#define IDD_BTN_CANCEL        660

